# Generated by Django 3.1.5 on 2021-04-17 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opna', '0002_remove_news_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'News'},
        ),
    ]
