# Generated by Django 3.1.5 on 2021-04-16 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('headtitle', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('level', models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), (
                    'B1', 'B1'), ('B2', 'B2'), ('C1', 'C1')], default='A1', max_length=2)),
                ('image', models.CharField(
                    default='https://images.pexels.com/photos/5088008/pexels-photo-5088008.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260', max_length=1000)),
                ('excerpt', models.CharField(blank=True, max_length=300)),
                ('published', models.BooleanField(default=False)),
                ('day', models.CharField(max_length=2)),
                ('month', models.CharField(max_length=2)),
                ('year', models.CharField(max_length=4)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('text', models.CharField(blank=True, max_length=300)),
                ('text_content', models.TextField(blank=True)),
                ('vocab_one', models.CharField(blank=True, max_length=200)),
                ('vocab_one_mean', models.TextField(blank=True)),
                ('vocab_two', models.CharField(blank=True, max_length=200)),
                ('vocab_two_mean', models.TextField(blank=True)),
                ('vocab_three', models.CharField(blank=True, max_length=200)),
                ('vocab_three_mean', models.TextField(blank=True)),
                ('vocab_four', models.CharField(blank=True, max_length=200)),
                ('vocab_four_mean', models.TextField(blank=True)),
                ('vocab_five', models.CharField(blank=True, max_length=200)),
                ('vocab_five_mean', models.TextField(blank=True)),
                ('grammer', models.CharField(blank=True, max_length=300)),
                ('grammer_content', models.TextField(blank=True)),
                ('example_one', models.TextField(blank=True)),
                ('example_two', models.TextField(blank=True)),
                ('example_three', models.TextField(blank=True)),
                ('example_four', models.TextField(blank=True)),
                ('example_five', models.TextField(blank=True)),
                ('writing', models.CharField(blank=True, max_length=300)),
                ('writing_content', models.TextField(blank=True)),
                ('listening', models.CharField(blank=True, max_length=300)),
                ('listening_content', models.TextField(blank=True)),
            ],
        ),
    ]
