# Generated by Django 3.1.5 on 2021-04-17 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opsa', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='story',
            options={'verbose_name_plural': 'Stories'},
        ),
    ]
