# Generated by Django 3.1.5 on 2021-04-17 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriber', '0005_auto_20210417_1652'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriber',
            old_name='subscriptionLevel',
            new_name='level',
        ),
    ]
